name: kelompok_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # pub.dev
  page_transition: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/aritmatika.png
    - assets/images/bangun_datar.png

    # aritmatika
    - assets/images/aritmatika/penjumlahan.png
    - assets/images/aritmatika/pengurangan.png
    - assets/images/aritmatika/pembagian.png
    - assets/images/aritmatika/perkalian.png
    - assets/images/aritmatika/modulus.png
    - assets/images/aritmatika/perpangkatan.png

    # bangun_datar
    - assets/images/bangun_datar/segitiga.png
    - assets/images/bangun_datar/persegi.png
    - assets/images/bangun_datar/persegi_panjang.png
    - assets/images/bangun_datar/jajar_genjang.png
    - assets/images/bangun_datar/layang_layang.png
    - assets/images/bangun_datar/lingkaran.png
    - assets/images/bangun_datar/trapesium.png
    - assets/images/bangun_datar/belah_ketupat.png

    # segitiga
    - assets/images/rumus/luas_segitiga.jpg
    - assets/images/rumus/keliling_segitiga.jpg
    - assets/images/rumus/alas_segitiga.jpg
    - assets/images/rumus/tinggi_segitiga.jpg

    # persegi
    - assets/images/rumus/luas_persegi.jpg
    - assets/images/rumus/keliling_persegi.jpg

    # persegi_panjang
    - assets/images/rumus/luas_persegi_panjang.jpg
    - assets/images/rumus/keliling_persegi_panjang.jpg

    # jajar_genjang
    - assets/images/rumus/luas_jajar_genjang.jpg
    - assets/images/rumus/keliling_jajar_genjang.jpg

    # layang_layang
    - assets/images/rumus/luas_layang_layang.jpg
    - assets/images/rumus/keliling_layang_layang.jpg

    # lingkaran
    - assets/images/rumus/luas_lingkaran.jpg
    - assets/images/rumus/keliling_lingkaran.jpg

    # trapesium
    - assets/images/rumus/luas_trapesium.jpg
    - assets/images/rumus/keliling_trapesium.jpg

    # belah_ketupat
    - assets/images/rumus/luas_belah_ketupat.jpg
    - assets/images/rumus/keliling_belah_ketupat.jpg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
